/*Given a string, we have to find out all subsequences of it.\
 A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

Follow up:

Can you come up with an alogrithm that don't have index as parameter
 in its recursive function?

Input:
abc

Output:
abc ab ac a bc b c  */

import java.util.*;
import java.util.Scanner;

public class Main {
    public static void printSubsequence(String str, String ans, int index) {
        if (index == str.length()) {
            if (ans.length() > 0)
                System.out.print(ans + " ");
            return;
        }
        printSubsequence(str, ans + str.charAt(index), index + 1); // taking character at index
        printSubsequence(str, ans, index + 1);// not taking that character at index
    }

    public static void main(String args[]) {
        Scanner sc = new Scanner(System.in);
        String str = sc.nextLine();
        printSubsequence(str, "", 0);
    }
}